### PR TITLE
#4 Enable front 30 pin USB connector; enable NVMeFix

### PR DESCRIPTION
**Pull request by alwynpan**
- Enable front 30 pin USB connector at USB 2.0 speed. Not able to enable it at USB 3.2 speed due to 15 ports limit.
- Enable NVMeFix
- Enable OpenShell
- Fix multiple monitors wake up issue (force all monitors online)
- Fix typos and markdown lint issues in README

### CODE REVIEW

**Comment by plutosherry** [comment]
okay thx! i will wait for @Baio1977  pull and test ^_^

**Comment by Lorys89** [comment]
> * Enable front 30 pin USB connector at USB 2.0 speed. Not able to enable it at USB 3.2 speed due to 15 ports limit.
> * Enable NVMeFix
> * Enable OpenShell
> * Fix multiple monitors wake up issue (force all monitors online)
> * Fix typos and markdown lint issues in README

its usb mapping is made to measure for its use of the pc, if you do not like it create a tailor-made one for you
openshell does not need it, add it to your efi, nvme fix is not mandatory for all nvme, in his case it works with and without therefore optional
for the monitor wake problem, he uses gpu does not need online force, he must use usbw ssdt and kext usbwakefixup. 
for redame fixes open an issue.
good evening

**Comment by alwynpan** [comment]
@Lorys89 thank you for the feedback.

> its usb mapping is made to measure for its use of the pc, if you do not like it create a tailor-made one for you

There are 13 USB ports mapped and there are two spares. So I thought it might be helpful to utilize the two spares to make the front USB ports functional. Also, those two are the only two that are not mapped. 

> nvme fix is not mandatory for all nvme, in his case it works with and without therefore optional

The system would boot and work without the NVMeFix kext. However, what the NVMeFix kext does is to fix the idle power management on non-Apple NVMe SSDs. Without it, non-Apple NVMe SSDs won't enter idle state.

> for the monitor wake problem, he uses gpu does not need online force, he must use usbw ssdt and kext usbwakefixup.

It was fixed in the `UHD 630` configuration where I believe this is for iGPU only, so this fix is kinda required.

Thank you.

**Comment by Lorys89** [comment]
> @Lorys89 thank you for the feedback.
> 
> > its usb mapping is made to measure for its use of the pc, if you do not like it create a tailor-made one for you
> 
> There are 13 USB ports mapped and there are two spares. So I thought it might be helpful to utilize the two spares to make the front USB ports functional. Also, those two are the only two that are not mapped.
> 
> > nvme fix is not mandatory for all nvme, in his case it works with and without therefore optional
> 
> The system would boot and work without the NVMeFix kext. However, what the NVMeFix kext does is to fix the idle power management on non-Apple NVMe SSDs. Without it, non-Apple NVMe SSDs won't enter idle state.
> 
> > for the monitor wake problem, he uses gpu does not need online force, he must use usbw ssdt and kext usbwakefixup.
> 
> It was fixed in the `UHD 630` configuration where I believe this is for iGPU only, so this fix is kinda required.
> 
> Thank you.

modify the pr, leave the bootarg -v and put on false "AuthRestart set to YES (Enables Authenticated restart for FileVault 2 so password is not required on reboot. Can be considered a security risk so optional)" he does not use FileVault 2, remove the bootarg igfxonln=1 and patch igpu force-online 01000000 data, and add ssdt-usbw (add inside to SSDT-GA Z490M Gaming X.aml) and kext usbwakefixup https://github.com/osy/USBWakeFixup , and remove OpenShell.
Apply some changes also for efi GPU, except that of the force online.

**Comment by alwynpan** [comment]
@Lorys89 I have updated the PR based on the feedback.

- Put back `-v` and set `AuthRestart` back to `false`
- Removed `igfxonln=1` from `boot-args` and added `force-online` to `<01000000>`
- Removed `openshell.efi`
- Added `USBWakeFixup` kext

However, I am not sure how to integrate the USBWakeFixup to `SSDT-GA Z490M Gaming X.aml`, would you please help?

Also not quite sure about what do you want me to do with

> Apply some changes also for efi GPU, except that of the force online.

**Comment by alwynpan** [comment]
On a side note, I have tried with the USBWakeFixup kext and SSDT (as a separate SSDT), and it didn't seem to work. Also tried to tweak a few USB wake-up-related settings in BIOS, no luck. Once the computer enters the sleep, it won't be able to be waked up by key strokes or mouse clicks/movement.

**Comment by Lorys89** [comment]
> On a side note, I have tried with the USBWakeFixup kext and SSDT (as a separate SSDT), and it didn't seem to work. Also tried to tweak a few USB wake-up-related settings in BIOS, no luck. Once the computer enters the sleep, it won't be able to be waked up by key strokes or mouse clicks/movement.

dont use ssdt gprw!

**Comment by alwynpan** [comment]
I am not familiar with SSDT. Would you please help on this side?

**Pull request closed without merging**
